### ISSUE TITLE
Price attribute can't be converted to float and gest dropped

### ISSUE THREAD

**Issue by alephcero** [urbansim/scraper2#2]
When cleaning all listings csv files [here](https://github.com/urbansim/scraper2/blob/charity_engine/scraper2/scraper2.py#L264-L277), converters turn into floats some prices than can be turned into floats. This happens because of 3 main reasons:
- `,` within the number as thousands separator
- `.` within the number as thousands separator
- A misplaced space (` `) used as thousands separator or following one of the previous.
- Nonunicode normalized characters like `\xa0`

Using simple regex expressions and unicode normalization goes a long way in the samples of data we tested. Eventually, we could move forward and create a more complex procedure within `_toFloat()` involving more cases.

**Comment by sablanchard** [comment]
solved in https://github.com/urbansim/scraper2/pull/3
